---

services:
  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    networks:
      macvlan0:
        ipv4_address: 10.24.24.83 # the IP of the container
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=America/Mexico_City
      - ServerIP=10.24.24.83
    ports:
      - ${PORT:-8191}:8191
    restart: unless-stopped

networks:
  macvlan0:   # externally created network
    external: true