---
services:
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr    
    networks:
      macvlan0:
         ipv4_address: 10.24.24.90 # the IP of the container
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Mexico_City
      - ServerIP=10.24.24.90
    volumes:
      - /srv/dev-disk-by-uuid-79a618dc-2955-4d54-b68e-650186fa473c/Docker/overseerr:/config
    ports:
      - 5055:5055
    restart: unless-stopped

networks:
  macvlan0:   # externally created network
    external: true