---

services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    networks:
      macvlan0:
        ipv4_address: 10.24.24.92 # the IP of the container
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Mexico_City
      - ServerIP=10.24.24.92
    volumes:
      - /srv/dev-disk-by-uuid-79a618dc-2955-4d54-b68e-650186fa473c/Docker/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped

networks:
  macvlan0:   # externally created network
    external: true